// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using advisor.Persistence;

namespace advisor.Migrations.pgsql
{
    [DbContext(typeof(PgSqlDatabase))]
    partial class PgSqlDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("advisor.Persistence.DbEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("FactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TurnId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("TurnId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("advisor.Persistence.DbFaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<long>("TurnId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TurnId");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("advisor.Persistence.DbGame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EngineVersion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemoteGameOptions")
                        .HasColumnType("text");

                    b.Property<string>("RulesetName")
                        .HasColumnType("text");

                    b.Property<string>("RulesetVersion")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("advisor.Persistence.DbPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FactionName")
                        .HasColumnType("text");

                    b.Property<int?>("FactionNumber")
                        .HasColumnType("integer");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("LastTurnNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("advisor.Persistence.DbRegion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Entertainment")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.Property<int>("Tax")
                        .HasColumnType("integer");

                    b.Property<string>("Terrain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalWages")
                        .HasColumnType("integer");

                    b.Property<long>("TurnId")
                        .HasColumnType("bigint");

                    b.Property<int>("UpdatedAtTurn")
                        .HasColumnType("integer");

                    b.Property<double>("Wages")
                        .HasColumnType("double precision");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.Property<int>("Z")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TurnId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("advisor.Persistence.DbReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FactionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FactionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TurnId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TurnId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("advisor.Persistence.DbStructure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Flags")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Needs")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SailDirections")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer");

                    b.Property<long>("TurnId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.Property<int>("Z")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("TurnId");

                    b.ToTable("Structures");
                });

            modelBuilder.Entity("advisor.Persistence.DbStudyPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Study")
                        .HasColumnType("text");

                    b.Property<string>("Teach")
                        .HasColumnType("text");

                    b.Property<long>("TurnId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("UniversityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TurnId");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("advisor.Persistence.DbTurn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("advisor.Persistence.DbUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("FactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Flags")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<bool>("OnGuard")
                        .HasColumnType("boolean");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<long?>("StrcutureId")
                        .HasColumnType("bigint");

                    b.Property<long>("TurnId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("RegionId");

                    b.HasIndex("StrcutureId");

                    b.HasIndex("TurnId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("advisor.Persistence.DbUniversity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("advisor.Persistence.DbUniversityMembership", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("UniversityId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "UniversityId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("UniversityMemberships");
                });

            modelBuilder.Entity("advisor.Persistence.DbUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("advisor.Persistence.DbEvent", b =>
                {
                    b.HasOne("advisor.Persistence.DbFaction", "Faction")
                        .WithMany("Events")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("advisor.Persistence.DbTurn", "Turn")
                        .WithMany("Events")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("advisor.Persistence.DbFaction", b =>
                {
                    b.HasOne("advisor.Persistence.DbTurn", "Turn")
                        .WithMany("Factions")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("advisor.Persistence.DbPlayer", b =>
                {
                    b.HasOne("advisor.Persistence.DbGame", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("advisor.Persistence.DbUser", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("advisor.Persistence.DbRegion", b =>
                {
                    b.HasOne("advisor.Persistence.DbTurn", "Turn")
                        .WithMany("Regions")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("advisor.Persistence.DbSettlement", "Settlement", b1 =>
                        {
                            b1.Property<long>("DbRegionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DbRegionId");

                            b1.ToTable("Regions");

                            b1.WithOwner()
                                .HasForeignKey("DbRegionId");
                        });

                    b.OwnsMany("advisor.Persistence.DbExit", "Exits", b1 =>
                        {
                            b1.Property<long>("RegionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Direction")
                                .HasColumnType("text");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Terrain")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.Property<int>("Z")
                                .HasColumnType("integer");

                            b1.HasKey("RegionId", "Direction");

                            b1.ToTable("Regions_Exits");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");

                            b1.OwnsOne("advisor.Persistence.DbSettlement", "Settlement", b2 =>
                                {
                                    b2.Property<long>("DbExitRegionId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("DbExitDirection")
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .HasColumnType("text");

                                    b2.Property<string>("Size")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DbExitRegionId", "DbExitDirection");

                                    b2.ToTable("Regions_Exits");

                                    b2.WithOwner()
                                        .HasForeignKey("DbExitRegionId", "DbExitDirection");
                                });

                            b1.Navigation("Settlement");
                        });

                    b.OwnsMany("advisor.Persistence.DbItem", "Products", b1 =>
                        {
                            b1.Property<long>("RegionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<int?>("Amount")
                                .HasColumnType("integer");

                            b1.HasKey("RegionId", "Code");

                            b1.ToTable("Regions_Products");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");
                        });

                    b.OwnsMany("advisor.Persistence.DbTradableItem", "ForSale", b1 =>
                        {
                            b1.Property<long>("RegionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<int>("Price")
                                .HasColumnType("integer");

                            b1.HasKey("RegionId", "Code");

                            b1.ToTable("Regions_ForSale");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");
                        });

                    b.OwnsMany("advisor.Persistence.DbTradableItem", "Wanted", b1 =>
                        {
                            b1.Property<long>("RegionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<int>("Price")
                                .HasColumnType("integer");

                            b1.HasKey("RegionId", "Code");

                            b1.ToTable("Regions_Wanted");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");
                        });

                    b.Navigation("Exits");

                    b.Navigation("ForSale");

                    b.Navigation("Products");

                    b.Navigation("Settlement");

                    b.Navigation("Turn");

                    b.Navigation("Wanted");
                });

            modelBuilder.Entity("advisor.Persistence.DbReport", b =>
                {
                    b.HasOne("advisor.Persistence.DbPlayer", "Player")
                        .WithMany("Reports")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("advisor.Persistence.DbTurn", "Turn")
                        .WithMany("Reports")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("advisor.Persistence.DbStructure", b =>
                {
                    b.HasOne("advisor.Persistence.DbRegion", "Region")
                        .WithMany("Structures")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("advisor.Persistence.DbTurn", "Turn")
                        .WithMany("Structures")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("advisor.Persistence.DbSailors", "Sailors", b1 =>
                        {
                            b1.Property<long>("DbStructureId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int>("Current")
                                .HasColumnType("integer");

                            b1.Property<int>("Required")
                                .HasColumnType("integer");

                            b1.HasKey("DbStructureId");

                            b1.ToTable("Structures");

                            b1.WithOwner()
                                .HasForeignKey("DbStructureId");
                        });

                    b.OwnsOne("advisor.Persistence.DbTransportationLoad", "Load", b1 =>
                        {
                            b1.Property<long>("DbStructureId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int>("Max")
                                .HasColumnType("integer");

                            b1.Property<int>("Used")
                                .HasColumnType("integer");

                            b1.HasKey("DbStructureId");

                            b1.ToTable("Structures");

                            b1.WithOwner()
                                .HasForeignKey("DbStructureId");
                        });

                    b.OwnsMany("advisor.Persistence.DbFleetContent", "Contents", b1 =>
                        {
                            b1.Property<long>("StructureId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Type")
                                .HasColumnType("text");

                            b1.Property<int>("Count")
                                .HasColumnType("integer");

                            b1.HasKey("StructureId", "Type");

                            b1.ToTable("Structures_Contents");

                            b1.WithOwner()
                                .HasForeignKey("StructureId");
                        });

                    b.Navigation("Contents");

                    b.Navigation("Load");

                    b.Navigation("Region");

                    b.Navigation("Sailors");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("advisor.Persistence.DbStudyPlan", b =>
                {
                    b.HasOne("advisor.Persistence.DbTurn", "Turn")
                        .WithMany("Plans")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("advisor.Persistence.DbUnit", "Unit")
                        .WithOne("Plan")
                        .HasForeignKey("advisor.Persistence.DbStudyPlan", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("advisor.Persistence.DbUniversity", "University")
                        .WithMany("Plans")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("advisor.Persistence.DbSkill", "Target", b1 =>
                        {
                            b1.Property<long>("DbStudyPlanId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<int?>("Days")
                                .HasColumnType("integer");

                            b1.Property<int?>("Level")
                                .HasColumnType("integer");

                            b1.HasKey("DbStudyPlanId");

                            b1.ToTable("StudyPlans");

                            b1.WithOwner()
                                .HasForeignKey("DbStudyPlanId");
                        });

                    b.Navigation("Target");

                    b.Navigation("Turn");

                    b.Navigation("Unit");

                    b.Navigation("University");
                });

            modelBuilder.Entity("advisor.Persistence.DbTurn", b =>
                {
                    b.HasOne("advisor.Persistence.DbPlayer", "Player")
                        .WithMany("Turns")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("advisor.Persistence.DbUnit", b =>
                {
                    b.HasOne("advisor.Persistence.DbFaction", "Faction")
                        .WithMany("Units")
                        .HasForeignKey("FactionId");

                    b.HasOne("advisor.Persistence.DbRegion", "Region")
                        .WithMany("Units")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("advisor.Persistence.DbStructure", "Structure")
                        .WithMany("Units")
                        .HasForeignKey("StrcutureId");

                    b.HasOne("advisor.Persistence.DbTurn", "Turn")
                        .WithMany("Units")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("advisor.Persistence.DbCapacity", "Capacity", b1 =>
                        {
                            b1.Property<long>("DbUnitId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int>("Flying")
                                .HasColumnType("integer");

                            b1.Property<int>("Riding")
                                .HasColumnType("integer");

                            b1.Property<int>("Swimming")
                                .HasColumnType("integer");

                            b1.Property<int>("Walking")
                                .HasColumnType("integer");

                            b1.HasKey("DbUnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("DbUnitId");
                        });

                    b.OwnsOne("advisor.Persistence.DbItem", "ReadyItem", b1 =>
                        {
                            b1.Property<long>("DbUnitId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int?>("Amount")
                                .HasColumnType("integer");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DbUnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("DbUnitId");
                        });

                    b.OwnsOne("advisor.Persistence.DbSkill", "CombatSpell", b1 =>
                        {
                            b1.Property<long>("DbUnitId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<int?>("Days")
                                .HasColumnType("integer");

                            b1.Property<int?>("Level")
                                .HasColumnType("integer");

                            b1.HasKey("DbUnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("DbUnitId");
                        });

                    b.OwnsMany("advisor.Persistence.DbItem", "Items", b1 =>
                        {
                            b1.Property<long>("UnitId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<int?>("Amount")
                                .HasColumnType("integer");

                            b1.HasKey("UnitId", "Code");

                            b1.ToTable("Unit_Items");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.OwnsMany("advisor.Persistence.DbSkill", "CanStudy", b1 =>
                        {
                            b1.Property<long>("UnitId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<int?>("Days")
                                .HasColumnType("integer");

                            b1.Property<int?>("Level")
                                .HasColumnType("integer");

                            b1.HasKey("UnitId", "Code");

                            b1.ToTable("Unit_CanStudy");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.OwnsMany("advisor.Persistence.DbSkill", "Skills", b1 =>
                        {
                            b1.Property<long>("UnitId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<int?>("Days")
                                .HasColumnType("integer");

                            b1.Property<int?>("Level")
                                .HasColumnType("integer");

                            b1.HasKey("UnitId", "Code");

                            b1.ToTable("Unit_Skills");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.Navigation("CanStudy");

                    b.Navigation("Capacity");

                    b.Navigation("CombatSpell");

                    b.Navigation("Faction");

                    b.Navigation("Items");

                    b.Navigation("ReadyItem");

                    b.Navigation("Region");

                    b.Navigation("Skills");

                    b.Navigation("Structure");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("advisor.Persistence.DbUniversity", b =>
                {
                    b.HasOne("advisor.Persistence.DbGame", "Game")
                        .WithMany("Universities")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("advisor.Persistence.DbUniversityMembership", b =>
                {
                    b.HasOne("advisor.Persistence.DbPlayer", "Player")
                        .WithOne("UniversityMembership")
                        .HasForeignKey("advisor.Persistence.DbUniversityMembership", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("advisor.Persistence.DbUniversity", "University")
                        .WithMany("Members")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("University");
                });

            modelBuilder.Entity("advisor.Persistence.DbUser", b =>
                {
                    b.OwnsMany("advisor.Persistence.DbUserRole", "Roles", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Role")
                                .HasColumnType("text");

                            b1.HasKey("UserId", "Role");

                            b1.ToTable("Users_Role");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("advisor.Persistence.DbFaction", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("advisor.Persistence.DbGame", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Universities");
                });

            modelBuilder.Entity("advisor.Persistence.DbPlayer", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Turns");

                    b.Navigation("UniversityMembership");
                });

            modelBuilder.Entity("advisor.Persistence.DbRegion", b =>
                {
                    b.Navigation("Structures");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("advisor.Persistence.DbStructure", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("advisor.Persistence.DbTurn", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Factions");

                    b.Navigation("Plans");

                    b.Navigation("Regions");

                    b.Navigation("Reports");

                    b.Navigation("Structures");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("advisor.Persistence.DbUnit", b =>
                {
                    b.Navigation("Plan");
                });

            modelBuilder.Entity("advisor.Persistence.DbUniversity", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("advisor.Persistence.DbUser", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
